### ISSUE TITLE
lxr.json file contains invalid proxy setting

### ISSUE THREAD

**Issue by CroniD** [leanix/leanix-reporting-cli#15]
Hi there,

if one generates a report project without setting a proxy, then the `lxr.json` still contains the template code for it.

```json
{
  "host": "app.leanix.net",
  "apitoken": "foobar",
  "proxyURL": "%proxyURL%",
  "localPort": "8080"
}
```

After a `npm install`, the call `npm start` fails with:
```
npm start

> myreport@1.0.0 start D:\leanix\workspace\myreport
> lxr start

Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:80
```

Removing the invalid proxy setting solves the problem.

Best regards

**Comment by aleics** [comment]
Hello,

Thank you for your issue submission. With the latest release `1.0.0-beta.10`, an empty string will be used as default, if no proxy url has been given when calling `lxr init`. We will try to improve the initialisation step in the near future.

Best regards
