### ISSUE TITLE
Feature request: Add processing of css files to the webpack config

### ISSUE THREAD

**Issue by CroniD** [leanix/leanix-reporting-cli#2]
Hi there,

currently you have to put all css files of 3rd party libs in your "asset" folder. It would be great if you could refer these css files in your "main.css" as

```css
@import "node_modules/third-party-lib/3rd.css"
```
or in js files via

```javascript
import 'node_modules/third-party-lib/3rd.css'
```

Webpack should resolve and bundle these css files together with the "main.css".

An example of one tool which does this: https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-a-stylesheet

Please keep in mind that a css file can refer other css files and fonts and images. A good example is [bootstrap](https://www.npmjs.com/package/bootstrap).

Best regards

**Comment by psurrey** [comment]
Hi @CroniD ,

this has been added to the new version of reporting-cli. Thank you!
See: https://github.com/leanix/leanix-reporting-cli/releases/tag/1.0.0-beta.2

**Comment by CroniD** [comment]
Hi @psurrey ,

thank you. Where do I find the information how to use external css files? Use `@import` or may I use `import` statement in a js file?


Best regards

**Comment by CroniD** [comment]
Hi @psurrey ,

your changes won't work. I attached a demo project as an example.
[myreport.zip](https://github.com/leanix/leanix-reporting-cli/files/1295802/myreport.zip)

Please do the following to reproduce:

- npm install
- create a lxr.json file
- npm start

Now have a look in "src/index.js". Please uncomment the statements in line 2 and 3. Save the file and take a look in the browser console. There should be some errors.

Then comment these lines again and save and head over to "src/assets/main.css". Please uncomment the first 2 lines and save the css file. Take a look in the browser console: same errors should appear.


Best regards

**Comment by psurrey** [comment]
Hi @CroniD ,

thank you for your comment.
I have created a new release that should fix the issue: https://github.com/leanix/leanix-reporting-cli/releases/tag/1.0.0-beta.4

If you have an existing project, please apply the changes that I have made to the template project. See https://github.com/leanix/leanix-reporting-cli/commit/cfe90ca358248f89750853e453617032cb7b4e6c

Looking forward to your feedback.

**Comment by CroniD** [comment]
Hi @psurrey ,

sounds great. I changed all my reports and it looks fine. I'll test them tomorrow directly in my workspace and report back to you.


Best regards

**Comment by psurrey** [comment]
Hi @CroniD ,

any feedback on this? Can we close this issue?

Best regards

**Comment by CroniD** [comment]
Hi @psurrey ,

sry, I forgot. Yes, we can close this one. Works just fine. Thank you.


Best regards
