### ISSUE TITLE
Feature request: extend README.md to include project setup and scripts

### ISSUE THREAD

**Issue by CroniD** [leanix/leanix-reporting-cli#5]
Hi there,

the README.md template should include details for how to build the project and what scripts are available to use.

A template may produce a result like https://github.com/incowia/leanix-custom-reports/blob/pathfinder/pathfinder/vtables/cimmasterlist/README.md

Best regards

**Comment by psurrey** [comment]
Already fixed with: https://github.com/leanix/leanix-reporting-cli/commit/459799d388ce8c0bbe88cdc6c6ec21dcd089ad8d
