### ISSUE TITLE
Feature request: add the current node to engines.node in package.json

### ISSUE THREAD

**Issue by CroniD** [leanix/leanix-reporting-cli#7]
Hi there,

it would be nice if the cli may add the current node version (the one that was used to init the project) to `engines.node` in `package.json` as restriction.

E.g.

```json
{
	"engines": {
		"node": ">=6.11.1"
	}
}
```

Please keep in mind that the version that is used in the init process might be lower than the defined version one has to use for the cli. E.g. it is possible using 6.8 to use the cli. In this case you might consider using the defined minimum version of the cli instead.

BTW: Or you may add this restriction to the cli's `package.json`, so you don't have to look at this case at all.

BTW2: It may be wise to define `engines.npm` as well, but I'm not sure about that.

Best regards

**Comment by psurrey** [comment]
Hi,

The node version for the cli itself is now specified in its `package.json`. Furthermore the generated project will have the version of node it was created with in its `package.json`.

Thank you for helping us improve the tool!
