### ISSUE TITLE
Feature request: add a bundling script

### ISSUE THREAD

**Issue by CroniD** [leanix/leanix-reporting-cli#9]
Hi there,

it would be nice if you could add a bundling script to the toolset which basically creates the content in "dist". Sometimes one must resolve bundling issues, which are pretty though to track down at the moment.

Best regards

**Comment by psurrey** [comment]
Hi @CroniD,

we have now added a `lxr build` command which does exactly that (see https://github.com/leanix/leanix-reporting-cli/releases/tag/1.0.0-beta.5).
Thank you!

Best regards

**Comment by CroniD** [comment]
Hi @psurrey ,

it seems you forgot to update the templates, didn't you?

Best regards

**Comment by psurrey** [comment]
Hi @CroniD,

thank you for your comment. I indeed forgot to updated the templates - its now fixed.

Furthermore thank you for your advice on handling github issues - I will reopen the issue so you can check and close it.

Best regards

**Comment by CroniD** [comment]
Hi @psurrey ,

thank you for re-opening the issue. Your changes are looking good to me.
